<a href="https://colab.research.google.com/github/omartinez182/VMLS/blob/main/Python_Companion/VMLS_Python%2C_Ch_05_Linear_Independence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import math
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt

# 5.1,2 Linear Independence, Basis

In [3]:
#Cash Flows Ex
r = .05 #interest
e1 = np.array([1,0,0]) #initial payment
l1 = np.array([1,-(1+r),0]) #first loan: t0: $1, t1: paid back with interest
l2 = np.array([0,1,-(1+r)]) #second loan: t1: $1, t2: paid back with interest
c = [1,2,-3] #cash flow
#Expansion coefficients:
alpha3 = -c[2]/(1+r)
alpha2 = -c[1]/(1+r) - c[2]/(1+r)**2
alpha1 = c[0] + c[1]/(1+r) + c[2]/(1+r)**2 #NPV
e1, l1, l2, alpha1, alpha2, alpha3

(array([1, 0, 0]),
 array([ 1.  , -1.05,  0.  ]),
 array([ 0.  ,  1.  , -1.05]),
 0.18367346938775508,
 0.8163265306122449,
 2.857142857142857)

In [4]:
alpha1*e1 + alpha2 * l1 + alpha3*l2, c

(array([ 1.,  2., -3.]), [1, 2, -3])

# 5.3 Orthonormal Vectors

In [5]:
a1,a2,a3 = np.array([0,0,-1]),np.array([1,1,0])/math.sqrt(2), np.array([1,-1,0])/math.sqrt(2)
npl.norm(a1),npl.norm(a2),npl.norm(a3), np.inner(a1,a2),np.inner(a1,a3),np.inner(a2,a3)

(1.0,
 0.9999999999999999,
 0.9999999999999999,
 0.0,
 0.0,
 -2.2371143170757382e-17)

In [6]:
x = [1,2,3]
beta1,beta2,beta3 = np.inner(a1,x),np.inner(a2,x),np.inner(a3,x)
xexp = beta1*a1 + beta2*a2 + beta3*a3
beta1,beta2,beta3, xexp, x #expansion of x in basis unchanged 

(-3, 2.1213203435596424, -0.7071067811865475, array([1., 2., 3.]), [1, 2, 3])

# 5.4 Gram-Schmidt

In [36]:
def gram_schmidt(a, tol=1e-10):
  q = []
  for i in range(len(a)):
    q_hat = a[i]
    for j in range(i):
      q_hat = q_hat - np.inner(q[j],a[i])*q[j]
    if npl.norm(q_hat) < tol:
      print("Vectors are linearly dependent")
    q.append(q_hat/npl.norm(q_hat))
  return q

In [37]:
a = np.array([[-1,1,-1,1],[-1,3,-1,3],[1,3,5,7]])

In [38]:
q = gram_schmidt(a)
q, npl.norm(q[0]), np.inner(q[0],q[1]),np.inner(q[0],q[2]),npl.norm(q[2]), np.inner(q[1],q[2]), npl.norm(q[2])

([array([-0.5,  0.5, -0.5,  0.5]),
  array([0.5, 0.5, 0.5, 0.5]),
  array([-0.5, -0.5,  0.5,  0.5])],
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0)

In [43]:
#Linear dependence via linear combination of a0 and a1
b = [a[0],a[1],1.3*a[0] + .5*a[1]]
gram_schmidt(b), b

Vectors are linearly dependent


([array([-0.5,  0.5, -0.5,  0.5]),
  array([0.5, 0.5, 0.5, 0.5]),
  array([-0.5,  0.5, -0.5,  0.5])],
 [array([-1,  1, -1,  1]),
  array([-1,  3, -1,  3]),
  array([-1.8,  2.8, -1.8,  2.8])])

In [45]:
#Linear dependence via linear combination of three 2-vecs
three_two_vecs = np.array([[1,1],[1,2],[-1,1]])
gram_schmidt(three_two_vecs)

Vectors are linearly dependent


[array([0.70710678, 0.70710678]),
 array([-0.70710678,  0.70710678]),
 array([-0.9486833 , -0.31622777])]